% [x, v, dtSat] = getSatPos ( t, PRN, PRNorbits, o, PR )
% 
% computes the position, velocity and clock correction for the satellites
% 
% t........... time of reception (2x1) / t(1)=WN, t(2)=TOW
% PRN......... the PRN of the satellites to get the information for
% PRNorbits... the PRN of the matching ephemerides in o
% PR.......... the pseudorange measurements for the satellites in <PRN>
function [x, v, dtSat] = getSatPos( t, PRN, PRNorbits, o, PR )

c = 299792458;
x = zeros(length(PRN),3);
v = zeros(length(PRN),3);
dtSat = zeros(length(PRN),1);
ts = zeros(1,length(PRN));

for p=1:length(PRN)
    % find best match for the Parameter-Set
    dt = inf;
    k = 0;
    for l=1:length(PRNorbits)
        if PRNorbits(l)==PRN(p) && abs(t(2) - o(l).time) < dt && (t(2) - o(l).time)>=0
            k = l;
            dt = abs(t(2)-o(l).time);
        end
    end

    eph = [PRN(p) ...
        o(k).a_f2 ...
        o(k).M_0 ...
        o(k).rootA ...
        o(k).deltan ...
        o(k).e ...
        o(k).omega ...
        o(k).C_uc ...
        o(k).C_us ...
        o(k).C_rc ...
        o(k).C_rs ...
        o(k).i_0 ...
        o(k).iDot ...
        o(k).C_ic ...
        o(k).C_is ...
        o(k).Omega_0 ...
        o(k).omegaDot ...
        o(k).t_oe ...
        o(k).a_f0 ...
        o(k).a_f1 ...
        o(k).time ...
        o(k).T_GD];

    % correct for the transmission time
    t_sent = t(2) - PR(PRN(p))/c;
    t_sent = t_sent - satclk( t_sent, eph );
    ts(p) = t_sent;
    
    x(p,:) = satpos( t_sent, eph ); % satellite position at transmission time
    v(p,:) = satvel( t_sent, eph ); % satellite velocity at transmission time
    dtSat(p) = satclk( t_sent, eph ); % satellite clock correction at tx time
end